@WebApiRabbitMQ_HostAddress = http://localhost:5261

POST {{WebApiRabbitMQ_HostAddress}}/solicitar-relatorio/reltorio%201
Accept: application/json

###

GET {{WebApiRabbitMQ_HostAddress}}/relatorios
Accept: application/json

POST {{WebApiRabbitMQ_HostAddress}}/relatorios
Accept: application/json

###GET 
